Feature/move tasks on column deletion
EllenSandqvist/kanban_collab pull request #9
Opened 2024-04-19 14:37 UTC by Chargermaster

When confirming to keep tasks on column deletion they are now moved to the column at index 0 and deletes the old tasks from local storage.

2024-04-19 14:40 UTC, annaisakson approved these changes

2024-04-19 14:42 UTC, Regni requested changes
if the first column is deleted the tasks are also gone, this should be fixed before merge with main

2024-04-20 12:03 UTC, Regni approved these changes
It works now!

2024-04-22 06:08 UTC, EthanHunt711 approved these changes

2024-04-22 06:18 UTC, EllenSandqvist approved these changes
Ser bra ut!

2024-04-22 09:39 UTC, closed without merging